### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by loboere** [PlayVoice/lora-svc#26]
!python svc_trainer.py -c config/maxgan.yaml -n lora -p model_pretrain/maxgan_pretrain.pth

Batch size per GPU : 4
2023-04-01 21:56:46.421916: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-01 21:56:47.377551: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-01 21:56:48,342 - INFO - NumExpr defaulting to 2 threads.
----------0----------
2023-04-01 21:56:48,782 - INFO - Resuming from checkpoint: model_pretrain/maxgan_pretrain.pth
----------25----------
Validation loop: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/lora-svc/svc_trainer.py", line 44, in <module>
    train(0, args, args.checkpoint_path, hp, hp_str)
  File "/content/lora-svc/utils/train.py", line 109, in train
    validate(hp, args, model_g, model_d, valloader, stft, writer, step, device)
  File "/content/lora-svc/utils/validation.py", line 37, in validate
    mel_loss = mel_loss / len(valloader.dataset)
ZeroDivisionError: float division by zero

I think the lora-svc/filelists/eval.txt file is the problem
  when i copy some samples from lora-svc/filelists/train.txt to lora-svc/filelists/eval.txt it starts training
  That is ok?

**Comment by MaxMax2016** [comment]
NumExpr defaulting to 2 threads.
----------0----------
2023-04-01 21:56:48,782 - INFO - Resuming from checkpoint: model_pretrain/maxgan_pretrain.pth
----------25----------

print for debug display 0 item

**Comment by MaxMax2016** [comment]
assert sr == self.hp.audio.sampling_rate 这个是需要先将数据处理为16KHz @seq2193

**Comment by seq2193** [comment]
#@title 重采样到16000Hz
!pip install pydub

import os
from pydub import AudioSegment

# 输入目录
input_dir = "/content/lora-svc/dataset_raw"

# 输出目录
output_dir = "/content/lora-svc/data_svc/waves"

# 目标采样率
target_sr = 16000

# 遍历输入目录中的所有WAV文件
for filename in os.listdir(input_dir):
    if filename.endswith(".wav"):
        # 加载原始音频文件
        audio = AudioSegment.from_wav(os.path.join(input_dir, filename))
        # 转换采样率
        audio = audio.set_frame_rate(target_sr)
        # 保存到输出目录
        output_filename = os.path.splitext(filename)[0] + f"_{target_sr}Hz.wav"
        audio.export(os.path.join(output_dir, output_filename), format="wav")
转换好了,出现跟1楼一样的错误

**Comment by MaxMax2016** [comment]
把配置文件里面的eval.txt直接改成train.txt呢

**Comment by seq2193** [comment]
> 把配置文件裡面的eval.txt直接改成train.txt呢 @seq2193 或者 https://github.com/PlayVoice/lora-svc/blob/main/utils/dataloader.py#L56-L71會檢測錯誤文件，可以在裡面添加打印，看具體是哪個文件、以及什麼原因導向致的；其中，如果音頻太短了，也會丟掉的。

这个我不太会改，filelist/eval.txt 似乎没有产生新文件还是用 猫雷的
还有 train.txt 路径有 // 会不会出错？
![52](https://user-images.githubusercontent.com/109962092/229687650-37eaddf2-0f29-4a80-a0be-d5bfd61f14c0.PNG)

**Comment by MaxMax2016** [comment]
把train.txt的前5条剪切，覆盖eval. txt的内容

**Comment by seq2193** [comment]
成功了  可以跑训练了

**Comment by VekkaAi** [comment]
me too. code don`t edit eval.txt

**Comment by MaxMax2016** [comment]
eval is created by hand, not auto created
