### ISSUE TITLE
这个是显存不够吗？

### ISSUE THREAD

**Issue by Chromer163** [PlayVoice/lora-svc#32]
Traceback (most recent call last):
  File "svc_trainer.py", line 46, in <module>
    train(0, args, args.checkpoint_path, hp, hp_str)
  File "/home/yango/code/Thin-Plate-Spline-Motion-Model/third_party/DINet/third_party/lora-svc/utils/train.py", line 109, in train
    validate(hp, args, model_g, model_d, valloader, stft, writer, step, device)
  File "/home/yango/code/Thin-Plate-Spline-Motion-Model/third_party/DINet/third_party/lora-svc/utils/validation.py", line 22, in validate
    mel_fake = stft.mel_spectrogram(fake_audio.squeeze(1))
  File "/home/yango/code/Thin-Plate-Spline-Motion-Model/third_party/DINet/third_party/lora-svc/utils/stft.py", line 90, in mel_spectrogram
    center=self.center, pad_mode='reflect', normalized=False, onesided=True, return_complex=False)
  File "/home/yango/.conda/envs/dinet/lib/python3.7/site-packages/torch/functional.py", line 607, in stft
    normalized, onesided, return_complex)
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by MaxMax2016** [comment]
torch是什么版本呢？

**Comment by Chromer163** [comment]
4090显卡，torch.__version__==1.12.0

**Comment by MaxMax2016** [comment]
我用3060 6G的笔记本跑的微调，应该不是显存不够；

应该是这个问题：https://github.com/pytorch/pytorch/issues/88038

**Comment by xiank1** [comment]
这个问题我也遇到了。
我在服务器上用linux和p4的卡，以及torch2.0.0+cu118，会偶尔遇到，在从头在进行环境的构建之后就几乎不会在遇到。
我在3060 6G的笔记本上也遇到了，我无法从头训练，但是我可以继续训练。
