### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by IsEddy** [PlayVoice/lora-svc#63]
按照readme跑的，上周还能跑起来，这周就不行了（

**Comment by MaxMax2016** [comment]
有更详细的错误信息没有？

**Comment by IsEddy** [comment]
F:\Desktop\lora-svc>python svc_trainer.py -c config/maxgan.yaml -n lora
Batch size per GPU : 4
----------5----------
2023-05-21 11:08:57,209 - INFO - Start from pretrain model: model_pretrain/maxgan_pretrain_48K_5L.pth
2023-05-21 11:08:58,589 - INFO - Starting new training run.
Traceback (most recent call last):
  File "F:\Desktop\lora-svc\svc_trainer.py", line 44, in <module>
    train(0, args, args.checkpoint_path, hp, hp_str)
  File "F:\Desktop\lora-svc\utils\train.py", line 107, in train
    trainloader = create_dataloader(hp, True)
  File "F:\Desktop\lora-svc\utils\dataloader.py", line 33, in create_dataloader
    dataset = FeatureFromDisk(hp, train)
  File "F:\Desktop\lora-svc\utils\dataloader.py", line 53, in __init__
    self._filter()
  File "F:\Desktop\lora-svc\utils\dataloader.py", line 58, in _filter
    for wavpath, pitch, ppg, spk in self.items:
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by MaxMax2016** [comment]
训练文件train.txt里面多了空白行？

**Comment by IsEddy** [comment]
是的是的，怪不得😂
