### ISSUE TITLE
 num_samples=0

### ISSUE THREAD

**Issue by sergedahdouh** [PlayVoice/lora-svc#88]
----------0----------
Traceback (most recent call last):
  File "/content/lora-svc/prepare/preprocess_zzz.py", line 14, in <module>
    trainloader = create_dataloader(hp, True)
  File "/content/lora-svc/utils/dataloader.py", line 35, in create_dataloader
    return DataLoader(dataset=dataset, batch_size=hp.train.batch_size, shuffle=True,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
any idea

**Comment by MaxMax2016** [comment]
maybe there has error, when do step 0~ step 7, you can check the steps before.

**Comment by sergedahdouh** [comment]
> maybe there has error, when do step 0~ step 7, you can check the steps before.

thank you for your reply, the issue is coming that in the file where train.txt is empty
